# Generated by Django 3.2.4 on 2021-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
