# Generated by Django 3.2.4 on 2021-06-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_like_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
